ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* "^/cms/(.*)") {
        rewrite ^/cms/(.*) /$1 break;
      }
  hosts:
    - host: regels.overheid.nl
      paths:
        - path: /cms/
          pathType: Prefix
  tls:
    - secretName: regels-overheid-nl-tls
      hosts:
        - regels.overheid.nl
imagePullSecrets:
  - name: regels-overheid-nl
image:
  tag: latest
configSecretName: cms-doppler-config