services:
  cms:
    depends_on:
      - postgres
    restart: always
    build:
      context: .
      dockerfile: apps/cms/dockerfile.dev
    volumes:
      - ./apps/cms/config:/code/apps/cms/config
      - ./apps/cms/database:/code/apps/cms/database
      - ./apps/cms/public:/code/apps/cms/public
      - ./apps/cms/src:/code/apps/cms/src
    ports:
      - 9001:9001
    environment:
      - ADMIN_JWT_SECRET=admin-jwt-secret
      - API_TOKEN_SALT=token-salt
      - APP_KEYS=a,b,c
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSL=false
      - JWT_SECRET=jwt-secret
      - PUBLIC_URL=http://cms.localhost
  docs:
    restart: always
    build:
      context: .
      dockerfile: apps/docs/dockerfile.dev
    volumes:
      - ./apps/docs/src:/code/apps/docs/src
      - ./apps/docs/docs:/code/apps/docs/docs
      - ./apps/docs/static:/code/apps/docs/static
      - ./apps/docs/sidebar.js:/code/apps/docs/sidebar.js
    ports:
      - 9002:9002
  web:
    restart: always
    build:
      context: .
      dockerfile: apps/web/dockerfile.dev
    volumes:
      - ./apps/web/src:/code/apps/web/src
      - ./apps/web/public:/code/apps/web/public
    ports:
      - 9000:9000
    environment:
      - CMS_API_URL=http://host.docker.internal:9001/api
      - NEXT_PUBLIC_CMS_ROOT_URL=http://cms.localhost
    extra_hosts:
      - host.docker.internal:host-gateway
  nginx:
    restart: always
    ports:
      - 80:80
    build:
      context: ./apps/nginx
      dockerfile: dockerfile.dev
  postgres:
    image: postgres:14.5
    container_name: postgres_dev
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=strapi
    ports:
      - 5433:5432
volumes:
  pgdata:
