services:
  cms:
    restart: always
    build:
      context: .
      dockerfile: apps/cms/dockerfile.prod
      args:
        DOPPLER_TOKEN: ${DOPPLER_TOKEN}
    ports:
      - 9001:9001
    volumes:
      - ./apps/cms/public:/app/public
    environment:
      - DOPPLER_TOKEN
  web:
    restart: always
    build:
      context: .
      dockerfile: apps/web/dockerfile.prod
    ports:
      - 9000:9000
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - DOPPLER_TOKEN
      - CMS_API_URL=http://cms:9001/api
  docs:
    restart: always
    build:
      context: .
      dockerfile: apps/docs/dockerfile.prod
    ports:
      - 9002:9002
  nginx:
    depends_on:
      - cms
      - web
      - docs
    restart: always
    ports:
      - 8080:80
    build:
      context: ./apps/nginx
      dockerfile: dockerfile.prod
