ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* "^/docs/(.*)") {
        rewrite ^/docs/(.*) /$1 break;
      }
  className: nginx
  hosts:
    - host: regels.overheid.nl
      paths:
        - path: /docs/
          pathType: Prefix
  tls:
    - secretName: regels-overheid-nl-tls
      hosts:
        - regels.overheid.nl
imagePullSecrets:
  - name: regels-overheid-nl