name: Validate pull request (web)

on:
  pull_request:
    paths:
      - 'apps/web/**'
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: MinBZK/regels.overheid.nl/.github/actions/run-workspace-script@main
        with:
          workspace: 'web'
          script: lint
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: MinBZK/regels.overheid.nl/.github/actions/run-workspace-script@main
        with:
          workspace: 'web'
          script: typecheck
  stylecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: MinBZK/regels.overheid.nl/.github/actions/run-workspace-script@main
        with:
          workspace: 'web'
          script: stylecheck
  build:
    needs: [lint, typecheck, stylecheck]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build (Docker)
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          file: ./apps/web/Dockerfile
          push: false
          build-args: |
            PUBLIC_URL=https://regels.overheid.nl/web/
            NEXT_PUBLIC_CMS_ROOT_URL=https://regels.overheid.nl/cms
            CMS_API_URL=https://regels.overheid.nl/cms/api
